Fix2x2 docs080
AlexanderLyNL/safestats pull request #25
Opened 2020-10-23 06:13 UTC by rosanneturner

small changes made in spring to 2x2 docs code, let's merge and clean up our branches

2020-10-23 08:43 UTC, AlexanderLyNL requested changes
Style comments.

2020-10-23 08:43 UTC, AlexanderLyNL commented on R/safe2x2Test.R
> +  calculate_p_theta_1 <- function(h) {
Preferably no underscores in names. I think that camelCasing is better.

2020-10-23 08:43 UTC, AlexanderLyNL commented on R/safe2x2Test.R
> +        not.satisfied <- FALSE
The dot notation is also not recommended anymore. I use a dot only to mimic `t.test` and `cor.test`, but those are aliases.

2020-11-19 15:30 UTC, rosanneturner commented
@AlexanderLyNL I have made those particular style changes; I propose to wait with adapting the rest of my part to camelcase untill I have made the major changes for the E variables, the code structure is going to change entirely anyway. Shall we now merge this branch, and the other one I requested? Then I'll make a fresh new branch from development to implement all the major changes I made with Peter!

2020-11-19 15:52 UTC, merged